[package]
name = "front"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["web"] }
dioxus-logger = "0.5.1"
shared = { path = "../shared" }
uuid = { version = "1.3.4", features = ["serde", "v4", "js"] }